
server {
    listen 80;
    index index.php;
    server_name api.localhost;
    root /var/www/html/public/;
    client_max_body_size 64M;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
    
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # "app" doit être le nom de ton service backend dans docker-compose
        fastcgi_pass backend:9000; 
        fastcgi_index index.php;
        
        # UTILISE DES GUILLEMETS ICI pour éviter l'erreur d'arguments
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
