
server {
    listen 80;
    server_name setupia.com www.setupia.com;
    
    location /api {
        # On envoie au conteneur "nginx_backend" sur son port interne
        proxy_pass http://nginx_backend:80; 
        
        # On transmet des infos utiles (qui est le client original ?)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location / {
        # On envoie au conteneur "frontend" sur son port interne
        proxy_pass http://frontend:80;
        
        # Pour React (et le routing history), on a parfois besoin de ça
        proxy_set_header Host $host;
    }
}
